### ISSUE TITLE
请问这个可以在局域网使用吗？

### ISSUE THREAD

**Issue by Greenhairturtle** [wbaizx/VideoLive#1]
就是两台手机在同一wifi下，使用socket连接，用这个可以做到吗？

**Comment by Greenhairturtle** [comment]
看了demo 明白了，不好意思啦

**Comment by wbaizx** [comment]
我测试的大部分手机（目前一般的手机）分辨率最大为1440*1080，所以设置1920*1080其实降低到手机的最大支持分辨率的。直播推流一般不会用这么大吧，性能也达不到啊。
然后采集分辨率是指从相机获取的原始数据的质量，用于录制高清一点的本地文件。理论上讲采集分辨率越大，对性能要求越高，如果性能达不到，就会掉帧，所以画面会卡。推流数据是从这里面缩放得到的，所以推流分辨率最好不大于采集分辨率。如果你不需要录制，那推流和采集用一样大小就可以。
采集码率只影响录制文件的质量，码率越大，质量越好，数据量也会越大。
推流码率同理只影响推流质量，同样码率越大，质量越好，数量量也同样增大。
一般的手机采集分辨率达到1280*720的时候就有点卡了，推流就根据需要设啦，我觉得480*320就够啦
码率的话1280*720,用1200左右吧，480*320 用500左右吧，这个你可以根据效果去调。H265的话码率可以降低近一半。
我也是个菜鸟，底层图片处理用的是C库了，这个性能我估计我也提不上去了。。

**Comment by Greenhairturtle** [comment]
谢谢您回复
我试了一下，在1280*720下确实就比较极限了

现在还有一个问题，就是推流的画面是黑白的
我看代码里面到最后数据是由I420转为了NV21
> ImagUtil.yuvI420ToNV12(data, input, pWidth, pHeight);
由于对这方面知识的缺乏，我确实不知道该怎么转换格式才可以正常显示颜色。
如果您知道的话，方便说一下吗？

再次谢谢您

**Comment by wbaizx** [comment]
我也是最近才发现，部分手机编码出来的画面是黑白的，这应该是的YUV格式问题
mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible);
这是编码器的配置，YUV420Flexible模糊了具体的yuv格式，有的手机支持YUV420Planar格式，我估计编码器默认选择了这种格式，而NV12是YUV420SemiPlanar格式，这种情况可以不转换I420或者指定编码器格式，经过测试颜色正常了，我刚刚修复了这个问题提交了。不知道你的情况是不是这种。

**Comment by Greenhairturtle** [comment]
最新的已经修复了这个问题！
谢谢您

**Comment by wbaizx** [comment]
不客气，
