### ISSUE TITLE
使用H265推流，H265接收端报错

### ISSUE THREAD

**Issue by a1b22003001** [wbaizx/VideoLive#14]
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received null jstring
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]     in call to GetStringUTFChars
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]     from void android.media.MediaCodec.native_configure(java.lang.String[], java.lang.Object[], android.view.Surface, android.media.MediaCrypto, int)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70] "Udp" prio=5 tid=34 Runnable
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   | group="main" sCount=0 dsCount=0 obj=0x12f11dd0 self=0x7f740b2000
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   | sysTid=25122 nice=0 cgrp=default sched=0/0 handle=0x7f75f79000
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   | state=R schedstat=( 9250769 2320768 117 ) utm=0 stm=0 core=0 HZ=100
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   | stack=0x7f74602000-0x7f74604000 stackSize=1036KB
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   | held mutexes= "mutator lock"(shared held)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at android.media.MediaCodec.native_configure(Native method)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at android.media.MediaCodec.configure(MediaCodec.java:590)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at com.library.live.vd.VDDecoder.beginCodec(VDDecoder.java:100)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   - locked <0x233eeef3> (a com.library.live.vd.VDDecoder)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at com.library.live.vd.VDDecoder.Information(VDDecoder.java:60)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at com.library.live.stream.UdpRecive.checkInformation(UdpRecive.java:214)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at com.library.live.stream.UdpRecive.mosaicVideoFrame(UdpRecive.java:182)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at com.library.live.stream.UdpRecive.write(UdpRecive.java:153)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at com.library.live.stream.UdpRecive$2.run(UdpRecive.java:119)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at android.os.Handler.handleCallback(Handler.java:815)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at android.os.Handler.dispatchMessage(Handler.java:104)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at android.os.Looper.loop(Looper.java:194)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70]   at android.os.HandlerThread.run(HandlerThread.java:61)
12-12 11:44:14.815 24984-25122/com.videolive A/art: art/runtime/check_jni.cc:70] 
12-12 11:44:14.816 24984-25122/com.videolive A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 25122 (Udp)

**Comment by a1b22003001** [comment]
使用H264推流和接收都没问题

**Comment by wbaizx** [comment]
因为是硬编，所以265要看手机的，有的手机是不支持H265硬编的

**Comment by a1b22003001** [comment]
找到原因了，我通过把h265的mediaCodec的sps打印出来，发现在VDDecoder的getH265information里information[i + 4]  有些手机是0x26 ,有些是0x28，把0x28的判断加上就可以播放了。

**Comment by a1b22003001** [comment]
h264也有出现这个问题，在getH264SPS 时，information[i + 4] == (byte) 0x68  判断里，部分手机是0x68，部分手机是0x28.   在getH264PPS时，OMX.IMG.TOPAZ.VIDEO.Encoder硬解 的 判断是 00 00 00 01 28  ---   00 00 00 01 25

**Comment by a1b22003001** [comment]
现在剩下的问题是，在魅族mx5里，安卓版本5.1， 在编码的时候无法输出关键帧

**Comment by wbaizx** [comment]
大佬啊。。这个几年我前做的，好久没有改过了

**Comment by wbaizx** [comment]
大佬啊。。这个我几年前做的，好久没有改过了

**Comment by a1b22003001** [comment]
不，你才是大佬，我现在还是对音视频这方面不了解呢，只能是站在巨人的肩膀上修改了一下

**Comment by wbaizx** [comment]
你如果要用的话，只能自己看看代码改了额，我很久没动过这个了，代码也有点老了

**Comment by a1b22003001** [comment]
没事，我继续调一下关键帧这个问题
